package exception

import (
	"testing"
)

func exceptionTest(t *testing.T) {
}
